### ISSUE TITLE
FireSSH doesn't fill in the whole window

### ISSUE THREAD

**Issue by wolfy1339** [mimecuvalo/firessh#33]
I'm having problems with FireSSH, it's not displaying in the whole window as showed in the screenshot.
I've never experienced this until recently.
Running on: Chrome 64bit

![image](https://cloud.githubusercontent.com/assets/4595477/5206283/dc474e10-756d-11e4-82f3-d68d9a4191ae.png)

**Comment by mimecuvalo** [comment]
Sorry for the delay in fixing this, it is now resolved in the latest version of FireSSH.
