### ISSUE TITLE
Addon for Firefox is not signed

### ISSUE THREAD

**Issue by beherit** [mimecuvalo/firessh#42]
Addon for Firefox is not signed and there is a problem with installation. In Firefox 43 is an option to turn off checking the addons signatures but this option will be removed in Firefox 44.

**Comment by beherit** [comment]
@mimecuvalo please take a look - we already have stable Firefox 44 and FireSSH stop working! :( Please fix it ASAP.

**Comment by mimecuvalo** [comment]
It should be already signed from the official website: https://addons.mozilla.org/en-US/firefox/addon/firessh/

**Comment by beherit** [comment]
@mimecuvalo You are wrong, addon is still unsigned :/ I install addon from official website and after restart Firefox I have message that addon is untrusted.

**Comment by mimecuvalo** [comment]
@beherit I cannot reproduce the bug you are seeing.  Can you show me a screenshot?  I checked on my end and it still seems fine.

**Comment by beherit** [comment]
![2016-03-22_083806](https://cloud.githubusercontent.com/assets/5073817/13944906/870534ea-f009-11e5-9586-b411301905a9.png)

I have this same on others devices with latest Firefox.

**Comment by mimecuvalo** [comment]
I went to that page to see if I could reproduce what you are seeing but I still don't see it on my machine.  Can you try uninstalling and reinstalling from https://addons.mozilla.org/en-US/firefox/addon/fireftp/ ?

**Comment by beherit** [comment]
I tried it many times on two others machines with others OS...

**Comment by mimecuvalo** [comment]
Sorry I meant to put a link for FireSSH.  I'm not seeing a problem for either FireSSH/FireFTP.  Do you have a colleague that's also seeing the same problem?  I haven't heard any other reports thus far.

**Comment by beherit** [comment]
May I ask my colleagues even I have this problem on other machines with others plugins? Sorry but this problem is only with FireSSH. Very important: after re-installation problem disappear BUT appear again after some time (e.g. I reinstall FireSSH 3 weeks ago and today problem appears again).

**Comment by mimecuvalo** [comment]
Yeah, if you can, ask your colleagues to see if they have this problem.  That's very strange that it's fine for a while and then it appears after some time...

**Comment by beherit** [comment]
So You don't gonna fix it? The problem is **only with FireSSH**.
