### ISSUE TITLE
Add autocomplete="off" to the <input> in blank.html

### ISSUE THREAD

**Issue by LMLB** [mimecuvalo/firessh#46]
If you have used a form containing a text input with the same name, an unwanted autocomplete dropdown will appear at the location of the cursor when you use FireSSH. This is pretty annoying since, whenever I press the up/down arrow keys, I have to use the mouse to click outside the dropdown to make it disappear.

**Comment by mimecuvalo** [comment]
will be fixed in next version.

**Comment by mimecuvalo** [comment]
thanks!
