### ISSUE TITLE
Make navigation to ssh:// urls work in e10s (electrolysis/multi-process) enabled Firefox

### ISSUE THREAD

**Issue by mayhemer** [mimecuvalo/firessh#52]
This is currently broken.  By default nsIProtocolHandler registered components are not visible to the content process.  Also, there is probably a need for some inter-process messaging to trigger action in the chrome process when the navigation happens on the content process (triggering protocol handler manually registered on the child).

See https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Multiprocess_Firefox_and_the_SDK for details and howtos.

**Comment by mimecuvalo** [comment]
fixed in https://github.com/mimecuvalo/firessh/commit/f7f8f6743aa855dc4ca9ae03ffe80ed6d7f29d08.

oy vey 10 years of trying to keep with all these compatibility changes :P
