### ISSUE TITLE
[Request]: relative file path for ssh key.

### ISSUE THREAD

**Issue by sinilill** [mimecuvalo/firessh#54]
Hi, would it be possible to make FireSSH config accept keys with a relative path, it seems right now a absolute path is supported. A relative path to the config file would be totally fine, thanks.

**Comment by mimecuvalo** [comment]
Relative to what though...?

**Comment by sinilill** [comment]
Relative to fireSSHsites.dat seems logical.

**Comment by mimecuvalo** [comment]
That file is saved in the Firefox profile which is platform dependent and can look like /Users/blah/Library/Application Support/Firefox/profiles/aoteunhnth3.default
 
This would be cumbersome to people.

**Comment by sinilill** [comment]
Well, somehow I would like to use it with Firefox Portable on a flash drive with a windows machine. On different machines flash drives have different drive letters and it's always a cumberstone to adjust the absolute path of the ssh key.
