### ISSUE TITLE
public key authentication error upon connect

### ISSUE THREAD

**Issue by atomsk81** [mimecuvalo/firessh#56]
using firefox latest and ubuntu 14.04

i'm connecting to a server with username/pass and I get the following error after adding the key to hash

Auth banner:
Authentication (publickey) failed.
Authentication failed

keep in mind that via linux terminal I can connect to same server successfully.

**Comment by mimecuvalo** [comment]
I removed that version of FireFTP (2.0.30) because it had a bad build that led to SFTP problems.
Please upgrade to 2.0.31 and Firefox 51.
