### ISSUE TITLE
Firessh for thunderbird

### ISSUE THREAD

**Issue by blackcrack** [mimecuvalo/firessh#63]
Hi,

mostly works some plugins in both Mozilla Application, so also in Thunderbird to ?
What's behind.. ?
ssh is a ssh/sftp connection tool.. so, also at first thinking behind, why not use a Browser for have a plugins in Firefox and Crome browser .. okey, but must you carry ever 2 apps carry anywher, why not one.. and a app where can you managing you mails too and where works also with the important tings, like Mails and news and so on.. na ja , or only mails, but mails be more important to giving directly informations, so, why not a support for telnet/ssh and so on in thunderbird.. to have a possible for connect directly a ssh-account like polarhome and so on via ssh-mail-plugin and check the mails via ssh/prompt on this server or managing maybe other things over ssh.. 
and this directly over thunderbird --profile ./profile as portable thunderbird with a execreator 
from 74.cz/en/app-starter-creator/index.php where can you create a exefile with swiches.
So, why then not directly in Thunderbird as Plugin and a extra Tab. and this portable mailprogram is on your usb-stick around your neck.

This about firessh for thunderbird.

best regards
Blacky

**Comment by mimecuvalo** [comment]
Hello, FireSSH is no longer under development (as it's not supported anymore by Mozilla).
